---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: all
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    #- verify
    - destroy
platforms:
  - name: trigger-pipelines-ubuntu18
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:ubuntu18
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    capabilities: ['NET_ADMIN']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: trigger-pipelines-ubuntu20
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:ubuntu20
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    capabilities: ['NET_ADMIN']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: trigger-pipelines-ubuntu22
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:ubuntu22
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: trigger-pipelines-debian10
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debian10
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: trigger-pipelines-debian11
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debian11
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: trigger-pipelines-debian12
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:debian12
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: trigger-pipelines-centos7
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:centos7
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: trigger-pipelines-rocky8
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:rocky8
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: trigger-pipelines-oraclelinux7
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:oraclelinux7
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: trigger-pipelines-oraclelinux8
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:oraclelinux8
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3
  - name: trigger-pipelines-oraclelinux9
    pre_build_image: true
    image: lotusnoir/ansible_molecule_test_images:oraclelinux9
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - python3

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
    host_vars:
      bullseye:
        ansible_python_interpreter: "/usr/bin/python3.9"
      bookworm:
        ansible_python_interpreter: "/usr/bin/python3.9"

verifier:
  name: ansible
