---
- name: "DEBUG | repo to deploy"
  ansible.builtin.debug:
    var: trigger_pipelines_repos_list
  when: trigger_pipelines_debug|bool

- name: "Remove prefix is exist"
  ansible.builtin.set_fact:
    projects: "{{ trigger_pipelines_repos_list | map('regex_replace', trigger_pipelines_remove_prefix, '') | list }}"
  when: trigger_pipelines_remove_prefix is defined

- name: "Trigger tasks"
  include_tasks: trigger.yml
  with_items: projects
